### ISSUE TITLE
[Invalid argument] Always getting Error unable to capture video stream: ffmpeg exited with code 1: /tmp/pfdxisl9vzzy

### ISSUE THREAD

**Issue by EnriqueWood** [prasanaworld/puppeteer-screen-recorder#1]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x] question about how to use this project

- **Summary**
I'm getting 
"Error unable to capture video stream: ffmpeg exited with code 1: /tmp/pfdxisl9vzzy: Invalid argument" no matter whether the path does or not exist. I already tried passing and not passing a path for ffmpg and both of them gave me the same error. Maybe I'm using this wrong?

 const recorder = new PuppeteerScreenRecorder(this.getPage(), {
            followNewTab: true,
            fps: 25,
        })
 await recorder.start('/tmp/pfdxisl9vzzy')

I tried creating and not creating the folder

**Comment by prasanaworld** [comment]
Hi EnriqueWood,

It would be great, if you could share the following to reproduce the scenario

1. Puppeteer-screen-recorder Version
2. Node version / NMP Version
2. Platform 
3. Architecture
4. Typescript project ?
5. Stack Error trace


Meanwhile I would also recommend to try without any option

```
const recorder = new PuppeteerScreenRecorder(this.khenshinPage.page)
```

if the above code succeed,  try passing `null` value to `fffmpeg_path`

```
{
     followNewTab: true,
    fps: 25,
    ffmpeg_Path: null
}
```

I Hope the above piece of code will solve your problem.

**Comment by EnriqueWood** [comment]
Puppeteer-screen-recorder Version: 1.1.1
Node version / NMP Version: v12.18.3
Platform: Kubuntu 20.04 64 bits kernel 5.4.0.66
Typescript project: yes
Stack Error trace: no stack trace, just the error mentioned above.

I Also tried without passing any config (using the default one), pointing it to my ffmpeg (/usr/bin/ffmpeg) and passing null. All with the same result.

**Comment by prasanaworld** [comment]
Hi EnriqueWood,

Thanks for sharing the details.

I'm able to reproduce the error. This is due to non-proper input passed to `start` method. The start method expects the path of the video, in which the path must specific the name of the video in mp4 format.

```
await recorder.start('/tmp/pfdxisl9vzzy')
```

**change the above code to**

```
await recorder.start('/tmp/pfdxisl9vzzy/test.mp4')
```

I Hope this works for you. Also, it gives me an opportunity to update the docs better :). Thanks

**Comment by prasanaworld** [comment]
Here you go, Document is updated.

https://prasanaworld.github.io/puppeteer-screen-recorder/classes/puppeteerscreenrecorder.html#start

**Comment by prasanaworld** [comment]
Closing this defect, Since the input argument passed is in the incorrect format.
