### ISSUE TITLE
Build directory not created for version 3.0.5

### ISSUE THREAD

**Issue by etaylor23** [prasanaworld/puppeteer-screen-recorder#108]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Build directory not created for version 3.0.5, 3.0.3 is fine.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by alopix** [comment]
Same issue, as can be inspected via the npm code tab: https://www.npmjs.com/package/puppeteer-screen-recorder/v/3.0.5?activeTab=code

**Comment by juanmav** [comment]
Same here. I rolled back to 3.0.3 and it started working again.

**Comment by trinitiwowka** [comment]
agree

**Comment by emilien-jegou** [comment]
This is still an issue, 3.0.5 is unusable

**Comment by prasanaworld** [comment]
Fixed: https://github.com/prasanaworld/puppeteer-screen-recorder/issues/113#issuecomment-2440160264. Closing because of duplicate
