### ISSUE TITLE
Any method to stop recording video

### ISSUE THREAD

**Issue by naveenkumarwittyparrot** [prasanaworld/puppeteer-screen-recorder#11]
Hi,.
I have a scenario, where there will be 2 APIs.
One is to start a recording(working fine).
and second is to stop the recording(here recording.stop() doesn't work).

Is any method available to stop recording? Means by process or any external events?

**Comment by prasanaworld** [comment]
Hi naveenkumarwittyparrot,

Thanks for raising your concern.

Could you please provide some sample code that will help me to reproduce this issue (recording.stop not working).

 Recording.stop should work in all cases. But I would to happy to understand if u can prove me wrong here. 
 
 Thanks

**Comment by naveenkumarwittyparrot** [comment]
Thanks for replying

In first API record.stop is working findKey

exports.startScreenRecord = async (req, res) => {
    const page = await browser.newPage();
    const recorder = new PuppeteerScreenRecorder(page, config);
    await page.goto(`https://qaapp.cleverpad.io/#/r/${meetingID}`, {
      waitUntil: 'load',
      timeout: 0,
    });
    await recorder.start(`zipData/${meetingID}.mp4`);

    // some delay
    await recorder.stop(); // here record.stop is working fine
    res.send('success');
}

But in next API i need to check how to stop it

exports.endScreenRecord = async (req, res) => {
    // how to stop recording here
    res.send('success');
  };

**Comment by prasanaworld** [comment]
Hey naveenkumarwittyparrot,

This something to do with your implementation of how to stop the screen recorder from multiple different endpoints.  This issue section is for reporting library-related issues.

For your question, The recorder object should be accessible in the same scope where u try to stop. If you call the stop method for the first time it returns true, further will yield false, indicating the stop method is already called.
