### ISSUE TITLE
If I initiate two recorders and stop one after another, the second one will halt

### ISSUE THREAD

**Issue by yidongw** [prasanaworld/puppeteer-screen-recorder#12]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
If I initiate two recorders and stop one after another, the second one would halt.
The second one would only save a portion of the whole video and will never resolve from `stop`

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by prasanaworld** [comment]
Hi yidongw,

Thanks for raising your concern.

Could you please provide some code so that I could reproduce the issue?  Also Please share the following information.
Node Version
NPM Version
Platform / OS
Hardware configuration
