### ISSUE TITLE
[Error message] :: Error detaching session Session already detached. Most likely the page has been closed.

### ISSUE THREAD

**Issue by ValeryMazharau** [prasanaworld/puppeteer-screen-recorder#14]
Getting this error: "Error detaching session Session already detached. Most likely the page has been closed." in console during test execution if recording is on.

Is there work around or possible solution how to disable this message?I am able to see recorded video, but message in console little bit confusing

I am using cucumber+puppeteer

**Comment by prasanaworld** [comment]
Hi @ValeryMazharau

Thanks for reaching out and raising your concern.

Could you please share the scenario under which your experience this issue? 

Kindly share a sample code to reproduce the same behavior. I would recommend you to try with the [latest version](https://github.com/prasanaworld/puppeteer-screen-recorder/releases/tag/v2.0.2) which has couple of bug fixes related to switching screen.

**Comment by prasanaworld** [comment]
Sorry I've accidentally closed this issue. Reopened it again.

**Comment by brianbrookes-wk** [comment]
I am getting this error as well. I am using version 2.0.2 
The case where we get it is when multiple tabs are opened (which are not being followed).

**Comment by brianbrookes-wk** [comment]
@prasanaworld Any update on this?

**Comment by niieani** [comment]
I'm getting this error when I start recording, stop recording, and then start the recording again on the same page.

**Comment by prasanaworld** [comment]
@niieani 

This is expected and as per design, once the recording is stopped it cannot be started again. 

If we start again, please create a new instance of the `PuppeteerScreenRecorder` with the same page.

```
  const recorder = new PuppeteerScreenRecorder(page);
  await recorder.start('./report/video/part1.mp4'); 
  // do something
  await recorder.stop();
  
  const recorder1 = new PuppeteerScreenRecorder(page);
  await recorder1.start('./report/video/part2.mp4');
  // do something
  await recorder1.stop();
```

**Comment by prasanaworld** [comment]
Hi @brianbrookes-wk,

Kindly accept my apology for the delayed response. 

The configuration which you provide seems good to me, However, If you could share a sample test logic under where your experience this issue would be helpful to reproduce the behavior effectively. (A sample code of the test shared in codepen would also help)

**Comment by niieani** [comment]
@prasanaworld I figured out that creating a separate instance is a workaround for this, however it doesn't feel too intuitive design-wise. Looking at the internals, it should be possible to reuse the same instance, as long as some of the state were to be reset as part of the `stop()` method. An issue I've had with recording with multiple instances is that sometimes there would be refed timeouts hanging the node process indefinitely, leading me to have to force quit the process with `process.exit()` at the end of the runtime. Something must not be getting cleaned up properly when multiple instances get attached to the same page. Interestingly, it only happens some of the time.

**Comment by Tomas2D** [comment]
Any progress on that?

**Comment by Tomas2D** [comment]
I proposed a solution to this problem in #21
