### ISSUE TITLE
Encoding Options

### ISSUE THREAD

**Issue by shshaw** [prasanaworld/puppeteer-screen-recorder#16]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
The ability to control FFMPEG's encoding options to change codec, quality, etc.

**Comment by prasanaworld** [comment]
The new [version 2.01](https://github.com/prasanaworld/puppeteer-screen-recorder/tree/v2.0.1) support stream.  

you can modify the codec, quality by transforming the stream to your needs. 


Please refer the documentation for more details [here](https://prasanaworld.github.io/puppeteer-screen-recorder/classes/puppeteerscreenrecorder.html#startstream).
