### ISSUE TITLE
Usage in Lambda functions

### ISSUE THREAD

**Issue by ziverlichson** [prasanaworld/puppeteer-screen-recorder#17]
*I'm submitting a ...*
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [X] question about how to use this project

*Summary*
Has anyone tried using this package inside an AWS Lambda function?

While locally it is working as expected, when trying to use it in a lambda function, I get an error. 
I deployed a simple lambda function with this package installed and I am getting the following error:
`"Missing path for FFmpeg, \n Set the FFMPEG_PATH env variable"`

This is the code for the lambda function:
```
const index = async (event, context, cb) => {
  const puppeteer = require('puppeteer-core')
  const chromium = require('chrome-aws-lambda')
  const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath,
    headless: chromium.headless
  })

  const { PuppeteerScreenRecorder } = require('puppeteer-screen-recorder')

  const page = await browser.newPage()
  const recorder = new PuppeteerScreenRecorder(page)
  const recordingsPath = path.resolve(`${os.tmpdir()}/`, 'recordings')
  const timeStamp = Math.floor(Date.now() / 1000)
  const fileName = `${timeStamp}-video.mp4`

  await recorder.start(`${recordingsPath}/video.mp4`)
  await page.waitForTimeout(2000)
  await recorder.stop()
}
```

**Comment by prasanaworld** [comment]
Hi @ziverlichson,

Thanks for reachout.

ffmpeg is one of the dependency for puppeteer-screen-recorder extension. 

It seems the path of the ffmpeg is not resolved properly inside AWS lambda function. 

Could you please ensure whether ffmpeg is installed in AWS environment (ideally it should be installed while installed Puppeteer-screen-recorder as part of dependency)?

you can also point the location the ffmpeg using `option.ffmpeg_Path`

**Comment by MiselKING** [comment]
There is also an option where you can use AWS Layers for `ffmpeg` and just point the location of the ffmpeg using `option.ffmpeg_Path` as suggested in the comment by @prasanaworld.
Below is the quick rundown of how to achieve this:
 - Download and unpack the latest static release build of FFmpeg for Linux amd64 of `ffmpeg` from [here](https://johnvansickle.com/ffmpeg/) (`ffmpeg-release-amd64-static.tar.xz`).
    - Once you download and unpack `.tar.xz` file you will also need to unpack `.tar` file (I was using `7-Zip` for this). 
 - Then create a folder `ffmpeg` (anywhere on your file system) and inside it a folder `bin` and inside `bin` folder put the file `ffmpeg` (it has no extension) that you got after unpacking the FFmpeg release build (there are more files/folders that you got after unpacking but you only need `ffmpeg` file)
 - Now zip the `ffmpeg` folder (the one we just created) to `.zip` extension
 - You can upload this `ffmpeg.zip` file anywhere to AWS S3 for the next step (I believe you can accomplish the next step even without upload but I am writing how it's done in the tutorial)
 - Next, go to AWS console, `Lambda > Layers` and create a new layer
     - Name: `ffmpeg`
     - Choose option `Upload a file from Amazon S3` (here you can also upload your `.zip` from file system)
         - Enter AWS S3 url where `ffmpeg.zip` file is located (if you selected `Upload a file from Amazon S3` option)
     - Choose a `runtime` you are using in your lambda function from the list (in tutorial it's `Python`, for me it was `Node.js 12x`)
     - For `Licence` enter this: `https://www.ffmpeg.org/legal.html`
     - Click `Create`
 - Now in your Lambda function, instantiate Puppeteer object like this:
```
const recorder = new PuppeteerScreenRecorder(page, { ffmpeg_Path: '/opt/bin/ffmpeg' });
```
 - When you create/upload your lambda function (manually, or using `serverless`) you will need to connect this layer we created to that lambda function. You do this by going into your lambda function, then in the `Code` section you will an option to `Add a layer` (click at the bottom). 
 - Choose `Custom Layers` and select the `ffmpeg` layer from dropdown list. For version, choose the latest (this is important if you replace your layer with a new version for example, initially it should be `1`).
 - Click `Add`. Now the `ffmpeg` layer should be connected to your function.

[Here](https://aws.amazon.com/blogs/media/processing-user-generated-content-using-aws-lambda-and-ffmpeg/) you can find the tutorial I was following when I was building `ffmpeg` with AWS.

Hope this helps.

**Comment by ziverlichson** [comment]
Hey @prasanaworld,
I was able to install and use your package within a lambda function! 🥳 
I followed @MiselKING's snippet to instantiate the recorder: `const recorder = new PuppeteerScreenRecorder(page, { ffmpeg_Path: '/opt/bin/ffmpeg' });`
The session is recorded and I am able to play it just fine, however, in my logs, I see this error message:
`Error unable to capture video stream: spawn /opt/bin/ffmpeg ENOENT`

Any idea why am I seeing this message and how can I fix it?

**Comment by prasanaworld** [comment]
Closing this issue, since no active discussions were made.

**Comment by geetpurwar** [comment]
When I tried to install it on lambda, unzip size is over 300+ MB
Anyways to reduce that?

I am already having Chrome and FFMPEG as separate layers.
