### ISSUE TITLE
Capture only the last X minutes

### ISSUE THREAD

**Issue by clouedoc** [prasanaworld/puppeteer-screen-recorder#22]
# Feature request

## Summary

I am using your package to troubleshoot production issues.
To save space, I would like to be able to save the last 30 minutes of a video, instead of saving the 30 first minutes.

## Current alternative

The current way to do this would be to process the whole output video / stream.

### Drawbacks of external processing

- it might require a high amount of disk space and memory to process

### Thanks

Thank you very much for this nice package, it makes my life easier!

**Comment by prasanaworld** [comment]
Hi @clouedoc,

we could achieve this easily by delaying `start` call and invoke it at 30th minute before it ends. 

``` 
/// execute some test
await recorder.start('<videoPath>');  // 30 minutes before it ends
// execute some other test
await recorder.stop()
```

**Comment by clouedoc** [comment]
Hello @prasanaworld 

I don't know in advance when the recording will end.
I currently use puppeteer-screen-recorder to troubleshoot production crashes.

I.e. I don't know if the crash will happen at t+20mn or t+40mn
