### ISSUE TITLE
Problems increasing length of video with recordDurationLength

### ISSUE THREAD

**Issue by toshvelaga** [prasanaworld/puppeteer-screen-recorder#24]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ x] question about how to use this project

- **Summary**
I am trying to make a recording for 10 seconds or potentially even longer. I am setting recordDurationLength to 10 but the recording only ends up being 3 seconds long. Any ideas as to what I am doing wrong? I've included my code with my Config below. Thank you!

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

```js
const puppeteer = require('puppeteer')
const { PuppeteerScreenRecorder } = require('puppeteer-screen-recorder')

const Config = {
  followNewTab: true,
  fps: 25,
  videoFrame: {
    width: 1024,
    height: 768,
  },
  aspectRatio: '4:3',
  recordDurationLength: 10,
}

;(async () => {
  const browser = await puppeteer.launch()
  const page = await browser.newPage()
  const recorder = new PuppeteerScreenRecorder(page, Config)
  await recorder.start('./report/video/spotify.mp4') // supports extension - mp4, avi, webm and mov
  await page.goto('https://open.spotify.com/episode/033bxIFePCK1JIy3wiBxBL')
  await recorder.stop()
  await browser.close()
})()
```

**Comment by prasanaworld** [comment]
Hi @toshvelaga,

Thanks for reaching out here.

The problem here is stop method is invoked before 10 seconds and causing recorder to stop as soon as it is invoked before the 10 seconds. 

Also, It gives me an opportunity to update the document stating the same as part of the next version.

Meanwhile, you could do something like this.
```
const puppeteer = require('puppeteer')
const { PuppeteerScreenRecorder } = require('puppeteer-screen-recorder')

const Config = {
  followNewTab: true,
  fps: 25,
  videoFrame: {
    width: 1024,
    height: 768,
  },
  aspectRatio: '4:3',
  recordDurationLength: 10,
}

const sleep = (time)  => new Promise((resolve) => setTimeout(resolve, time));

;(async () => {
  const browser = await puppeteer.launch()
  const page = await browser.newPage()
  const recorder = new PuppeteerScreenRecorder(page, Config)
  await recorder.start('./report/video/spotify.mp4') // supports extension - mp4, avi, webm and mov
  await page.goto('https://open.spotify.com/episode/033bxIFePCK1JIy3wiBxBL')
  await sleep(10 * 1000) /// await for 10 seconds. 
  await recorder.stop()
  await browser.close()
})()



```

**Comment by toshvelaga** [comment]
@prasanaworld Thanks so much for the fast reply! I see so technically it would seem that recordDurationLength has not been integrated into the library. Oh ok the await sleep(10 * 1000) method works great I also used  await page.waitForTimeout(10000) which seems to work.
