### ISSUE TITLE
Using FFmpeg underneath the hood to record the screen?

### ISSUE THREAD

**Issue by toshvelaga** [prasanaworld/puppeteer-screen-recorder#25]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [X] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
- Hi @prasanaworld, one last question about this library which is awesome btw! You are using FFmpeg underneath the hood to record the screen right? I am writing a medium article and am including your library in the article. Wanted to give a very brief description of how it works. Thanks so much.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by prasanaworld** [comment]
The Puppeteer-screen-recorder is making use of the chrome devtool protocol via stream to capture the page screenshot frame by fame and effectively combining the frame to write the frame to disk using the FFmpeg library.

capture frame stream -> collect the frames -> write to disk
