### ISSUE TITLE
Script hangs indefinitely and fails to produce any video

### ISSUE THREAD

**Issue by FractalHQ** [prasanaworld/puppeteer-screen-recorder#27]
- **I'm submitting a ...**
  [x] bug report

- **Summary**

When running a basic script from the documentation, the program simply hangs indefinitely.  It creates a `/test` directory, but nothing else.  I'm likely missing something simple as this is my first time using puppeteer.  I apologize if so!  Here is my basic implementation:

```js
import { PuppeteerScreenRecorder } from 'puppeteer-screen-recorder'
import { PassThrough } from 'stream'
import puppeteer from 'puppeteer'

const target = 'http://127.0.0.1:5500/test.html'
const savePath = './test/test.mp4'

const config = {
	followNewTab: false,
	fps: 25,
	videoFrame: {
		width: 1024,
		height: 768,
	},
	aspectRatio: '4:3',
	recordDurationLimit: 3,
}

const record = async () => {
	const browser = await puppeteer.launch()
	const page = await browser.newPage()
	await page.goto(target)

	const recorder = new PuppeteerScreenRecorder(page, config)
	await recorder.start(savePath)
	const pipeStream = new PassThrough()
	await recorder.startStream(pipeStream)

	await recorder.stop()
	await browser.close()
}

record()
```

I'm running the following:

node: v16.13.1
puppeteer-screen-recorder:  latest
os: latest MacOS

**Comment by FractalHQ** [comment]
I just realized I was starting a stream, but that's not what I want to do.  The README had the steps as 1 and 2, (as opposed to a or b), and I misunderstood that as meaning both steps are required.  My mistake!

**Comment by minipunch** [comment]
I did the exact same thing as you LOL

Should prob get that README to clarify a bit better lol
