### ISSUE TITLE
followNewTab is not effective

### ISSUE THREAD

**Issue by tb250** [prasanaworld/puppeteer-screen-recorder#28]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
```
 const browser = await puppeteer.launch({ headless: false, args: ['--window-size=1440,764', '--no-sandbox', '--disable-setuid-sandbox'] });
    const page = await browser.newPage();
    page.setViewport(defaultViewport);
    // 初始化录制器
    const recorder = new PuppeteerScreenRecorder(page, {
        followNewTab: true,
        videoFrame: defaultViewport,
        aspectRatio: '360:191'
    })
    // 开始录制，以日期为文件名
    recorder.start(`./screencast/${date}.mov`);

    await page.goto(baseUrl);
    await page.waitForTimeout(5000);

  const newPage = await browser.newPage();
        newPage.setViewport(defaultViewport);
        await newPage.goto(baseUrl);
        await newPage.waitForTimeout(4000);


    await recorder.stop();
```
it seems that `page.on('popup')` is not effective

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by mattpr** [comment]
I was playing with this library today and saw a bunch of issues including this one.  This was an easy fix and was just a programming error not covered by any tests.  I didn't add any tests, but fixed the issue.

Note that if you change the viewport size on your original page the output video is going to be based on that viewport size.  So if you use followNewTab and those new tabs have a different sized viewport, it will be squished into the viewport size of the original page.

I'm not sure exactly the intent/use-case of this feature as it isn't really documented (not to mention it didn't work)... but I would suggest only using this if you want to record a whole session starting with one window and then following tabs that are opened...where all tabs have same viewport size.

However as soon as a new tab is opened the new one is recorded.  If the original page opens multiple tabs the recording of the original window will stop and switch to each one as they are opened.  So lots of edge cases that may surprise end users of this lib.

**Comment by tb250** [comment]
could you tell me how would trigger `page.on('popup')`; Is that event defined By yourself?

**Comment by tb250** [comment]
It seems that `page.on('popup')` wasn't trigger on my computer
