### ISSUE TITLE
ffmpge path is missing

### ISSUE THREAD

**Issue by Arun-KumarH** [prasanaworld/puppeteer-screen-recorder#31]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ x] question about how to use this project

I use a below example from documentation:

```
const puppeteer = require('puppeteer');
const { PuppeteerScreenRecorder } = require('puppeteer-screen-recorder');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  const recorder = new PuppeteerScreenRecorder(page);
  await recorder.start('./report/video/simple.mp4'); // supports extension - mp4, avi, webm and mov
  await page.goto('https://example.com');

  await page.goto('https://test.com');
  await recorder.stop();
  await browser.close();
})();
```
but I get an error:
```
FFmpeg path is missing,
     Set the FFMPEG_PATH env variable
```

even if I provide the option of installed ffmpeg from node_modules as `{ffmpeg_Path: './node_modules/@ffmpeg-installer/ffmpeg'}` for `PuppeteerScreenRecorder` I get below error:
Error unable to capture video stream: spawn ./node_modules/@ffmpeg-installer/ffmpeg EACCES

Node version: 18.3.0
npm version: 8.11.0
Puppeteer version: 15.3.2
Puppeteer-screen-recorder Version: 2.0.2

**Comment by josvos** [comment]
Hi,

On my (Linux) system `./node_modules/@ffmpeg-installer/ffmpeg` is a directory and I found the ffmpeg program in `./node_modules/@ffmpeg-installer/linux-x64/ffmpeg`.  Maybe something similar is the case on your sysrem?  I didn't even know there was an ffmpeg included in node_modules, as I have set `ffmpeg_path` to `'/usr/bin/ffmpeg'`, the ffpmeg that is already installed on my system.

**Comment by prasanaworld** [comment]
Hi @Arun-KumarH, Thanks for raising your concern.

Could you please provide some code so that I could reproduce the issue? Also Please share the following information.
Node Version
NPM Version
Platform / OS
Hardware configuration

**Comment by prasanaworld** [comment]
I believe this issue is happening in Mac M1 machine, where the `@ffmpeg-installer/ffmpeg` is not returning  the path of the `ffmPeg`. 

I've update the `ffmPeg` dependency. It will be fixed in the upcoming release. Thanks again

**Comment by prasanaworld** [comment]
Fix has been rolled out as part of version: [2.0.3](https://www.npmjs.com/package/puppeteer-screen-recorder/v/2.0.3)

**Comment by spankyed** [comment]
Still getting this error on M1.

**Comment by Arun-KumarH** [comment]
@prasanaworld tested with new version 2.0.3, but still have the same issue:

```
@prasanaworld 
Node version - 18.3.0
NPM version - 8.11.0
OS - opensuse-tumbleweed
```
