### ISSUE TITLE
rmtp stream

### ISSUE THREAD

**Issue by danielehrhardt** [prasanaworld/puppeteer-screen-recorder#33]
- **I'm submitting a ...**
  [ ] bug report
  [X ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Is it possible to stream the output to a rtmp stream?
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by prasanaworld** [comment]
Hi @danielehrhardt, 

Thanks for reaching out to me..!! Currently the library doesn't support RTMP stream. But this is definitely something I want to add but not finding time to do it. 

I will add a feature request to do it in future. Thanks

**Comment by danielehrhardt** [comment]
https://github.com/restreamer/restreamer
