### ISSUE TITLE
improving framerate of CSS transitions

### ISSUE THREAD

**Issue by rctngle** [prasanaworld/puppeteer-screen-recorder#34]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x ] question about how to use this project

- **Summary**

I am recording a page that includes some CSS transitions. They are currently quite choppy in the rendered video. Some things I have tried with little effect:

1. changing the fps
2. using MOV rather than MP4
3. use Chrome rather than Chromium

I'd be very grateful for any ideas to record smoother transitions?

```(async () => {
	const url = '';
	const seconds = 26;
	const browser = await puppeteer.launch({
		defaultViewport: {
			width: 1080,
			height: 1920			
		}
	});
	const page = await browser.newPage();
	const Config = {
		followNewTab: false,
		fps: 25,
		videoFrame: {
			width: 1080,
			height: 1920,
		},
		recordDurationLimit: seconds,
		aspectRatio: '9:16',
	}

	const recorder = new PuppeteerScreenRecorder(page, Config);
	await page.goto(url, {waitUntil: 'networkidle0'});
	
	await recorder.start('./Processed-Test.mp4');

	await page.click('.column');
	setTimeout(async () => {
		await recorder.stop();
		await browser.close();
	}, seconds * 1000)

**Comment by prasanaworld** [comment]
Closing in favor of the  open issue. (https://github.com/prasanaworld/puppeteer-screen-recorder/issues/20)
