### ISSUE TITLE
Ability to record a video of a specific element

### ISSUE THREAD

**Issue by IlliaHryshkevych** [prasanaworld/puppeteer-screen-recorder#39]
- **I'm submitting a ...**
   feature request
  
- **Summary**
It would be great to have ability to record specific element. The same as puppeteer screenshot functionality works:

```
 await page.waitForSelector('#hplogo');          // wait for the selector to load
  const element = await page.$('#hplogo');        // declare a variable with an ElementHandle
  await element.screenshot({path: 'google.png'}); // take screenshot element in puppeteer
```

**Comment by prasanaworld** [comment]
Hi @IlliaHryshkevych, 

Thank for you request. This feature request is doesn't seems to be in align with `puppeter-screen-recorder`. Since this plugin focus on screen/Tab recording.

**Comment by florinvirdol** [comment]
Hi! 
I'm also interested in this feature. I'm thinking into forking your library and trying to add that functionality. 
Would that require a lot of changes? At first sight doesn't seems so, but, i think you know better, that's why i'm asking?
Thank you!
