### ISSUE TITLE
[Feature Request] :: Width and Height of the video must be setup

### ISSUE THREAD

**Issue by developingtoday** [prasanaworld/puppeteer-screen-recorder#5]
- **I'm submitting a ...**
  [ x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
With new versions the size of the video must be set up when you write the file on disk.
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by prasanaworld** [comment]
Hi developingtoday,

Thanks for reaching out. As per your request, added support for video frame width and height. Also provided the 
option to support the aspect ratio for the video.

Have a look at the documentation.
https://prasanaworld.github.io/puppeteer-screen-recorder/globals.html#videooptions

Latest NMP Version
npmjs.com/package/puppeteer-screen-recorder/v/1.1.9
