### ISSUE TITLE
Lambda

### ISSUE THREAD

**Issue by geetpurwar** [prasanaworld/puppeteer-screen-recorder#53]
Has anyone tried using this package inside an AWS Lambda function?

When I tried to zip and upload, the size comes around 379 MB which is larger than the lambda recommended size of 250MBs.

**Comment by prasanaworld** [comment]
Create a thread to discuss about using puppeteer-screen-recorder in AWS lambda. 

Please post your queries here
https://github.com/prasanaworld/puppeteer-screen-recorder/discussions/60
