### ISSUE TITLE
How to record mobile sized videos

### ISSUE THREAD

**Issue by mecirmartin** [prasanaworld/puppeteer-screen-recorder#65]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [x] question about how to use this project

- **Summary**
Hey, is there a way to record videos in mobile view? E.g. using mobile view in chromium?
I've tried doing this in pupetteer, setting viewport like this
```
await page.setViewport({
    width: 375,
    height: 667,
    isMobile: true,
  })
```

but puppeteer-screen-recorder still records whole page

**Comment by ackava** [comment]
@mecirmartin I am using following config to record mobile videos.

```typescript
await page.setUserAgent( "Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/70.0.3538.75 Mobile/15E148 Safari/605.1");
await page.setViewport({
    width: 375,
    height: 667,
    deviceScaleFactor: 1,
  });
```
I am not using `isMobile`.
