### ISSUE TITLE
[Enhancement] More file format support

### ISSUE THREAD

**Issue by n4cr** [prasanaworld/puppeteer-screen-recorder#9]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
I would like to be able to get a different video format particularly GIF.
- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by prasanaworld** [comment]
Hi @n4cr,

Thanks for submitting your feature request.

There is a priority feature request to support multiple video format output. But I don't think GIF is part of the scheme. 
Since GIF is considered an image format. 

This library is designed to handle screen recorded video format only.

**Comment by prasanaworld** [comment]
Support for transparent video background. (Different File formats) #13
